language: php
php:
- 5.6
- 7.0
- 7.1
- hhvm
env:
- DB=sqlite
- DB=mysql
matrix:
  fast_finish: true
  allow_failures:
    - php: "5.6"
    - php: "hhvm"
    - env: DB=mysql
install:
- travis_retry composer require satooshi/php-coveralls "^1" --no-update --dev --prefer-dist
- travis_retry composer install
before_script:
- rm -rf *.sqlite
- if [[ "$DB" == "pgsql" ]]; then vendor/maghead/maghead/travis/setup-pgsql ; fi
- if [[ "$DB" == "mysql" ]]; then vendor/maghead/maghead/travis/setup-mysql ; fi
- phpenv rehash
- php vendor/bin/maghead use tests/config/sqlite.yml
- php vendor/bin/maghead schema build -f
script:
- phpunit -c phpunit.xml.dist
after_success:
- php vendor/bin/coveralls -v
cache:
  apt: true
  directories:
  - vendor
