language: php
php:
- 7.0
install:
- travis_retry composer require satooshi/php-coveralls "^1" --no-update --dev --prefer-dist
- travis_retry composer install
before_script:
- phpenv rehash
- php vendor/bin/maghead use tests/config/sqlite.yml
- php vendor/bin/maghead schema build -f
script:
- phpunit -c phpunit.xml.dist
after_success:
- php vendor/bin/coveralls -v
cache:
  apt: true
  directories:
  - vendor
