language: php
php:
- 5.4
- 5.5
- 5.6
install:
- rm -rf vendor/corneltek/serializerkit
- travis_retry composer self-update
- travis_retry composer require satooshi/php-coveralls "^1.0" --no-update --dev
- travis_retry composer install
before_script:
- phpenv rehash
- php vendor/bin/lazy build-conf db/config/database.testing.yml
- php vendor/bin/lazy schema build -f
- php vendor/bin/lazy sql --rebuild
script: phpunit -c phpunit.xml.dist
after_success:
- php vendor/bin/coveralls -v
cache:
  apt: true
  directories:
  - vendor
notifications:
  slack:
    secure: X+iimYs9fGh3K9PYgupJNaQn322zwP7gPKH/9EIcFQbZrwJaWDPrZC578FfF5ArMvUVV4T0O84le1Lm5bO1BsFd8O4qvZ8za9X8z05Jn2v6zWpqxhtN+l1nmpo+8m0lAc78yYLGHOeRrQQnNdHqo3fUZqJMb+kYKQPB9kLOJnzM=
