---
bootstrap:
schema:
  auto_id: true
  paths:
   - tests
data_sources:
  default:
    # dsn: "mysql:host=localhost;dbname=actionkit_test"
    dsn: "sqlite:tests.db"
    # database: actionkit_test
    # user: root
    # pass:
