---
bootstrap:
schema:
  auto_id: true
  paths:
   - tests
data_source:
  default: sqlite
  nodes:
    mysql:
      dsn: "mysql:host=localhost;dbname=actionkit_test"
      # database: actionkit_test
      # user: root
      # pass:
    sqlite:
      dsn: "sqlite:tests.db"
